# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-07-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
