# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-07-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
